version: '3.8'

volumes:
    postgresql.data:

services:
    db:
        image: postgres:13
        container_name: postgres.docker
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - postgresql.data:/var/lib/postgresql/data
        networks:
            - global

networks:
    global:
